trigger:
  batch: true
  branches:
    include:
      - master

resources:
  containers:
  - container: nv-bionic-wasm
    image: nventive/wasm-build:1.3

pr:
  branches:
    include:
      - master
  paths:
    include:
    - '*'
    exclude:
    - '*.md'

variables:
- name: IsCanary
  value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/canaries')]

jobs:
  - job: Windows

    pool:
      name: 'Hosted Windows 2019 with VS2019'

    workspace:
      clean: all

    variables:
      - name: UnoPackageOutputPath
        value: $(Build.ArtifactStagingDirectory)
      - name: ANDROID_NDK_HOME
        value: C:\Microsoft\AndroidNDK64\android-ndk-r16b
      - name: ANDROID_NDK_PATH
        value: C:\Microsoft\AndroidNDK64\android-ndk-r16b
      - name: AndroidNdkDirectory
        value: C:\Microsoft\AndroidNDK64\android-ndk-r16b
      - group: 'UADO Keystore'

    strategy:
      maxParallel: 3
      matrix:
        Release_UWP:
          BuildPlatform: UWP
        Release_Android:
          BuildPlatform: Android
        Release_Wasm:
          BuildPlatform: Wasm

    steps:
    - powershell: Write-Host "##vso[task.setvariable variable=ApplicationBuildNumber;]$(Build.BuildId)"
      displayName: 'Set Canary version'
      condition: eq(variables['IsCanary'], 'true')

    - task: UseDotNet@2
      condition: and(succeeded(), eq(variables['IsCanary'], 'true'))
      inputs:
        packageType: 'runtime'
        version: '2.2.0'

    - task: nventiveCanaryUpdater@5
      condition: and(succeeded(), eq(variables['IsCanary'], 'true'))
      inputs:
        solution: 'src/Uno.AzureDevOps.sln'
        usePrivateFeed: false
        useNuGetOrg: true
        mergeBranch: true
        gitUserName: 'nventive DevOps'
        gitUserEmail: 'nv-devops@outlook.com'
        branchToMerge: 'master'
        nugetUpdaterVersion: '2.0.4'
        allowDowngrade: true
        packageAuthor: 'nventive'
        summaryFile: '$(UnoPackageOutputPath)/Canary.md'
        resultFile: '$(UnoPackageOutputPath)/update_result.json'
        additionalPublicSources: https://pkgs.dev.azure.com/uno-platform/1dd81cbd-cb35-41de-a570-b0df3571a196/_packaging/unoplatformdev/nuget/v3/index.json

    - task: GitVersion@4

    - task: NuGetToolInstaller@0
      inputs:
        versionSpec: 5.3.*

    - task: DownloadSecureFile@1
      condition: eq(variables['BuildPlatform'], 'Android')
      name: Keystore
      inputs:
        secureFile: nventive.jks

    - task: NuGetCommand@2
      inputs:
        command: restore
        restoreSolution: src/Uno.AzureDevOps.sln
        feedsToUse: 'config'
        nugetConfigPath: 'src/NuGet.config'

    - powershell: ((Get-Content src\Uno.AzureDevOps\Uno.AzureDevOps.Shared\Client\ClientConstants.cs -Raw) -Replace '--production-secret--','$(ProductionSecret)' -Replace '--staging-secret--','$(StagingSecret)').Trim() | Set-Content -Path src\Uno.AzureDevOps\Uno.AzureDevOps.Shared\Client\ClientConstants.cs -Encoding UTF8
      displayName: Set client secrets

    - powershell: ((Get-Content src\Uno.AzureDevOps\Uno.AzureDevOps.Shared\Client\ClientConstants.cs -Raw) -Replace '--appcenter-secret-android--','$(AppCenterSecretAndroid)').Trim() | Set-Content -Path src\Uno.AzureDevOps\Uno.AzureDevOps.Shared\Client\ClientConstants.cs -Encoding UTF8
      displayName: Set AppCenter secret

    - task: MSBuild@1
      inputs:
        solution: src/Uno.AzureDevOps.sln
        configuration: Release
        platform: $(BuildPlatform)
        restoreNugetPackages: false
        msbuildArguments: /p:AndroidSigningKeyStore=$(Keystore.secureFilePath) /p:AndroidSigningKeyAlias=$(AndroidSigningKeyAlias) /p:AndroidSigningKeyPass=$(AndroidSigningKeyPass) /p:AndroidSigningStorePass=$(AndroidSigningStorePass)

    - task: PublishBuildArtifacts@1
      inputs:
        ArtifactName: $(BuildPlatform)
        PathtoPublish: $(UnoPackageOutputPath)
        publishLocation: Container

  - job: linux
    container: nv-bionic-wasm

    pool:
      vmImage: 'ubuntu-16.04'

    variables:
      - name: NUGET_PACKAGES
        value: $(build.sourcesdirectory)/.nuget
      - name: UnoPackageOutputPath
        value: $(Build.ArtifactStagingDirectory)

    steps:
    - checkout: self
      clean: true

    - script: echo '##vso[task.setvariable variable=ApplicationBuildNumber;]$(Build.BuildId)'
      displayName: 'Set Canary version'
      condition: eq(variables['IsCanary'], 'true')

    - task: UseDotNet@2
      condition: and(succeeded(), eq(variables['IsCanary'], 'true'))
      inputs:
        packageType: 'runtime'
        version: '2.2.0'

    - task: nventiveCanaryUpdater@5
      condition: and(succeeded(), eq(variables['IsCanary'], 'true'))
      inputs:
        solution: 'src/Uno.AzureDevOps.sln'
        usePrivateFeed: false
        useNuGetOrg: true
        mergeBranch: true
        gitUserName: 'nventive DevOps'
        gitUserEmail: 'nv-devops@outlook.com'
        branchToMerge: 'master'
        nugetUpdaterVersion: '2.0.4'
        allowDowngrade: true
        packageAuthor: 'nventive'
        summaryFile: '$(UnoPackageOutputPath)/Canary.md'
        resultFile: '$(UnoPackageOutputPath)/update_result.json'
        additionalPublicSources: https://pkgs.dev.azure.com/uno-platform/1dd81cbd-cb35-41de-a570-b0df3571a196/_packaging/unoplatformdev/nuget/v3/index.json
    
    - bash: |
        cd ~
        git clone https://github.com/emscripten-core/emsdk
        cd emsdk
        ./emsdk install sdk-1.39.9
        ./emsdk activate sdk-1.39.9
      displayName: 'Setup Emscripten'

    - bash: |
        cd ~/emsdk
        wget https://raw.githubusercontent.com/mono/mono/27247739c68faee7b2a63ae805222d4b375d2161/sdks/builds/fix-emscripten-8511.diff
        cd ~/emsdk/upstream/emscripten
        patch -N -p1 < ~/emsdk/fix-emscripten-8511.diff

    - bash: |
        sed -i 's/--production-secret--/$(ProductionSecret)/g' ClientConstants.cs
        sed -i 's/--staging-secret--/$(StagingSecret)/g' ClientConstants.cs
        sed -i 's/--appcenter-secret-android--/$(AppCenterSecretAndroid)/g' ClientConstants.cs

      workingDirectory: $(build.sourcesdirectory)/src/Uno.AzureDevOps/Uno.AzureDevOps.Shared/Client/

    - script: |
        source ~/emsdk/emsdk_env.sh
        cd $(build.sourcesdirectory)
        msbuild /r /p:Configuration=Release $(build.sourcesdirectory)/src/Uno.AzureDevOps/Uno.AzureDevOps.Wasm/Uno.AzureDevOps.Wasm.csproj
      env:
        GITVERSION_FullSemVer: $(GITVERSION_FullSemVer)
      displayName: 'Build Uado'
    - task: CopyFiles@2
      displayName: 'Publish Wasm Binaries'
      inputs:
        SourceFolder: $(build.sourcesdirectory)/src/Uno.AzureDevOps/Uno.AzureDevOps.Wasm/bin/Release/netstandard2.0/dist
        Contents: '**/*.*'
        TargetFolder: $(build.artifactstagingdirectory)
        CleanTargetFolder: false
        OverWrite: false
        flattenFolders: false

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: $(build.artifactstagingdirectory)
        ArtifactName: Uno-AzureDevOps-wasm
        ArtifactType: Container
